// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA168AagVHdlIZTIXwsHgAk8k55wfDUp9w',
    appId: '1:369628611925:web:bfce28a90602df49e15bdc',
    messagingSenderId: '369628611925',
    projectId: 'chat-app-c033e',
    authDomain: 'chat-app-c033e.firebaseapp.com',
    storageBucket: 'chat-app-c033e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLr4mnvjbQ8mu2mbPQ6sW_SJhsQXtvbD8',
    appId: '1:369628611925:android:a3c102068563e8e9e15bdc',
    messagingSenderId: '369628611925',
    projectId: 'chat-app-c033e',
    storageBucket: 'chat-app-c033e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMJLQoQcu7Hv5XuAPLVQx9_0MhK4laQC4',
    appId: '1:369628611925:ios:ae79acdca6a2b8aee15bdc',
    messagingSenderId: '369628611925',
    projectId: 'chat-app-c033e',
    storageBucket: 'chat-app-c033e.appspot.com',
    iosClientId: '369628611925-7lg91ipcoc3dttmk41hmpp82jd8hj796.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMJLQoQcu7Hv5XuAPLVQx9_0MhK4laQC4',
    appId: '1:369628611925:ios:ae79acdca6a2b8aee15bdc',
    messagingSenderId: '369628611925',
    projectId: 'chat-app-c033e',
    storageBucket: 'chat-app-c033e.appspot.com',
    iosClientId: '369628611925-7lg91ipcoc3dttmk41hmpp82jd8hj796.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFb',
  );
}
